-- DATABASE AND TABLES EXPLORATION
SELECT 
    table_name,
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns
WHERE table_schema = 'public'
ORDER BY table_name, ordinal_position;


SELECT * FROM dim_customers LIMIT 5;
SELECT * FROM dim_products LIMIT 5;
SELECT * FROM fact_sales LIMIT 5;

-- cardinality
SELECT attname, n_distinct
FROM pg_stats 
WHERE tablename = 'dim_customers'
ORDER BY attname;

SELECT attname, n_distinct
FROM pg_stats 
WHERE tablename = 'dim_products'
ORDER BY attname;

SELECT attname, n_distinct
FROM pg_stats 
WHERE tablename = 'fact_sales'
ORDER BY n_distinct


-- DIMENSIONS EXPLORATION
SELECT DISTINCT 
    country
FROM dim_customers;

SELECT DISTINCT category FROM dim_products;
SELECT DISTINCT category, subcategory, product_name FROM dim_products order by 1,2,3;

-- DATE EXPLORATION
SELECT 
    MIN(order_date) first_order,
    MAX(order_date) last_order,
    (MAX(order_date) - MIN(order_date))/30 timespan_months
FROM fact_sales;


SELECT
    MIN(birthdate) earliest_birth_date,
    (CURRENT_DATE - MIN(birthdate))/365 oldest_age,
    MAX(birthdate) oldest_birth_date,
    (CURRENT_DATE - MAX(birthdate))/365 youngest_age
FROM dim_customers;

-- MEASURE EXPLORATION
SELECT
    'Total Sales' AS Measure,
    SUM(sales_amount) AS Value
FROM fact_sales

UNION ALL

SELECT
    'Total Items Sold' AS Measure,
    SUM(quantity) AS Value
FROM fact_sales

UNION ALL

SELECT
    'Average Selling Price' AS Measure,
    ROUND(AVG(price),2) AS Value
FROM fact_sales

UNION ALL

SELECT
    'Total Orders' AS Measure,
    COUNT(order_number) AS Value
FROM fact_sales

UNION ALL

SELECT
    'Total Customers' AS Measure,
    COUNT(fact_sales.customer_key) AS Value
FROM fact_sales

UNION ALL

SELECT
    'Total Customers with Order' AS Measure,
    COUNT(DISTINCT fact_sales.customer_key) AS Value
FROM fact_sales;


-- MAGNITUDE
-- total number of customers by country
SELECT
    country,
    COUNT(DISTINCT customer_key) Total_Customers
FROM dim_customers
GROUP BY country
ORDER BY COUNT(DISTINCT customer_key) DESC;

-- total customers by gender
SELECT 
    gender,
    COUNT(DISTINCT dim_customers.customer_key) Total_Customers
FROM dim_customers
GROUP BY gender;

--  total products by category
SELECT
    category,
    COUNT(product_id)
FROM dim_products
GROUP BY category
ORDER BY 
    CASE WHEN category IS NULL THEN 1 ELSE 0 END ASC,
    COUNT(product_id) DESC;


--  average costs in each category
SELECT
    category,
    ROUND(AVG(cost),2)
FROM dim_products
GROUP BY category
ORDER BY 
    CASE WHEN category IS NULL THEN 1 ELSE 0 END ASC,
    AVG(cost) DESC;


-- the total revenue generated for each category

SELECT
    p.category,
    SUM(f.sales_amount) total_revenue
FROM fact_sales f
LEFT JOIN dim_products p ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- total revenue generated by each customer
SELECT
    c.customer_key,
    SUM(f.sales_amount) total_revenue
FROM dim_customers c
LEFT JOIN fact_sales f ON c.customer_key = f.customer_key
GROUP BY c.customer_key
ORDER BY total_revenue DESC;


-- distribution of sold items across countries
SELECT
    c.country,
    COUNT(p.product_id) total_sold
FROM dim_products p
LEFT JOIN fact_sales f ON p.product_key = f.product_key
LEFT JOIN dim_customers c ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY 
    CASE WHEN c.country IS NULL THEN 1 ELSE 0 END ASC,
    total_sold DESC;


-- RANKING ANALYSIS
--  5 products generate the highest revenue
SELECT
    p.product_name,
    SUM(f.sales_amount) total_revenue
FROM fact_sales f
LEFT JOIN dim_products p ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY SUM(f.sales_amount) DESC
LIMIT 5;

--  5 worst-performing products in terms of sales?
SELECT
    p.product_name,
    SUM(f.sales_amount) total_revenue
FROM fact_sales f
LEFT JOIN dim_products p ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY SUM(f.sales_amount) ASC
LIMIT 5;


-- Top 10 customers who have generated the highest revenue

SELECT
    c.customer_id,
    MAX(c.first_name) first_name,
    MAX(c.last_name) last_name,
    SUM(f.sales_amount) total_sales
FROM dim_customers c
LEFT JOIN fact_sales f ON c.customer_key = f.customer_key
GROUP BY c.customer_id
ORDER BY SUM(f.sales_amount) DESC
LIMIT 10;


-- top 3 customers with fewest orders placed
SELECT
    c.customer_id,
    MAX(c.first_name) first_name,
    MAX(c.last_name) last_name,
    COUNT( DISTINCT f.order_number) total_orders
FROM dim_customers c
LEFT JOIN fact_sales f on c.customer_key = f.customer_key
GROUP BY c.customer_id
ORDER BY total_orders  ASC
LIMIT 3;